# Generated by Django 5.1.6 on 2025-02-19 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_orders_order_rename_products_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.ImageField(blank=True, default='/images/default.jpg', upload_to='images/category/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='No description available', max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, default='/images/default.jpg', upload_to='images/products/'),
        ),
    ]
