# Generated by Django 5.1.6 on 2025-02-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_cart_unique_user_product_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Processing'), (4, 'Delivered'), (5, 'Canceled')], default=1, max_length=50),
        ),
    ]
